import {
    Briefcase,
    User,
    Star,
    CheckCircle,
    Code,
    Palette,
    Coin,
    ShoppingBag,
    Airplane,
    Heart,
    GraduationCap,
    MagnifyingGlass,
    Book,
    Chat,
    Users,
    PaintBrush,
    Play,
    Gavel,
    Key,
    AddressBook,
    Link,
    Lightbulb,
    Note,
    File,
    Receipt,
    FolderOpenIcon,
    Tag,
    TerminalWindow,
} from '@phosphor-icons/react';
import type { Icon } from '@phosphor-icons/react';

export const TAG_ICONS: Record<string, Icon> = {
    Work: Briefcase,
    Personal: User,
    Important: Star,
    Todo: CheckCircle,
    Code: Code,
    Design: Palette,
    Finance: Coin,
    Shopping: ShoppingBag,
    Travel: Airplane,
    Health: Heart,
    Education: GraduationCap,
    Research: MagnifyingGlass,
    Reference: Book,
    Communication: Chat,
    Social: Users,
    Creative: PaintBrush,
    Media: Play,
    Legal: Gavel,
    Passwords: Key,
    Addresses: AddressBook,
    Links: Link,
    Ideas: Lightbulb,
    Notes: Note,
    Drafts: File,
    Receipts: Receipt,
    Paths: FolderOpenIcon,
    Commands: TerminalWindow,
};

/** Returns the icon component for a tag, falling back to the generic Tag icon. */
export function getTagIcon(tag: string): Icon {
    return TAG_ICONS[tag] ?? Tag;
}
